JCC = javac
JCR = java
JFLAGS = -g

CLASSES = \
	Nodes/And.java \
	Nodes/Implication.java \
	Nodes/Node.java \
	Nodes/Not.java \
	Nodes/Or.java \
	Nodes/Var.java \
	Main.java \
	Parser.java \
	Tokens.java

all:
	$(JCC) $(JFLAGS) $(CLASSES)

run: 
	java  Main